### ISSUE TITLE
博主，您的博客无法访问了

### ISSUE THREAD

**Issue by yzqzss** [guugg/Gridea-Theme-Art#1]
博主，您的博客 803344.xyz 很长时间都无法访问了，请问是换域名了吗？还是有其他问题？

**Comment by guugg** [comment]
> 博主，您的博客 803344.xyz 很长时间无法访问了，请问是换换了吗？还是有其他问题？

之前比较忙，后来登录gridea发生一些错误。 导致我直接不想维护这个主题了。

**Comment by yzqzss** [comment]
https://github.com/saveweb/doing/issues/3
